---

- name: Chezmoi Config - Initialize chezmoi (empty repository)
  ansible.builtin.command: "chezmoi init"
  when: not chezmoi_init_url

- name: Chezmoi Config - Initialize chezmoi from
  ansible.builtin.command: "chezmoi init --apply --verbose {{ chezmoi_init_url }}"
  when: chezmoi_init_url
  changed_when: false
