---

- name: Chezmoi - Check if app is already installed.
  ansible.builtin.command: chezmoi --version
  register: chezmoi_version_output
  ignore_errors: true
  changed_when: false

- name: Chezmoi - Get latest available version available for download.
  block:
    - name: Chezmoi - Find latest releases.
      ansible.builtin.uri:
        url: https://api.github.com/repos/twpayne/chezmoi/releases/latest
        return_content: true
      register: chezmoi_release_output
    - name: Chezmoi - Set latest available version for download.
      ansible.builtin.set_fact:
        chezmoi_version: "{{ chezmoi_release_output.json.tag_name }}"
  when: chezmoi_version_output.rc > 0

- name: Chezmoi - Set version to download and other variables.
  ansible.builtin.set_fact:
    chezmoi_install: "{{ chezmoi_version_output.rc == 2 or not(chezmoi_version in chezmoi_version_output.stdout) }}"
    chezmoi_version_filtered: "{{ chezmoi_version | regex_replace('^v', '') }}"

- name: Chezmoi - Ensure package is installed.
  block:
    - name: Chezmoi - Install for Linux (Debian Family).
      ansible.builtin.apt:
        deb: "{{ chezmoi_repository }}/releases/download/{{ chezmoi_version }}/chezmoi_{{ chezmoi_version_filtered }}_linux_{{ chezmoi_debian_architectures[ansible_architecture] }}.deb"
      when: ansible_system == "Linux" and ansible_facts['os_family'] == "Debian"

    - name: Chezmoi - Install for macOS using brew.
      community.general.homebrew:
        name: chezmoi
        state: present
        update_homebrew: true
      when: ansible_system == "Darwin"
  when: chezmoi_install
