---

- name: Chezmoi | Check if app is already installed
  ansible.builtin.command: chezmoi --version
  register: chezmoi_version_output
  ignore_errors: true
  changed_when: false
  tags:
    - dotfiles-install
    - dotfiles-install-mac
    - dotfiles-install-linux

- name: Chezmoi | Should we install
  ansible.builtin.set_fact:
    chezmoi_install: "{{ chezmoi_version_output.rc > 0 }}"
  tags:
    - dotfiles-install
    - dotfiles-install-mac
    - dotfiles-install-linux

- name: Chezmoi | Debug task
  ansible.builtin.debug:
    msg: "Existing chezmoi binary in system: {{ chezmoi_install | ternary(false,true) }}"
  tags:
    - dotfiles-install
    - dotfiles-install-mac
    - dotfiles-install-linux
