---

- name: Chezmoi - Check if app is already installed
  ansible.builtin.command: chezmoi --version
  register: chezmoi_version_output
  ignore_errors: true
  changed_when: false

- name: Chezmoi - Should we install
  ansible.builtin.set_fact:
    chezmoi_install: "{{ chezmoi_version_output.rc > 0 }}"

- name: Chezmoi - Debug task
  ansible.builtin.debug:
    msg: "Existing chezmoi binary in system: {{ chezmoi_install | ternary(false,true) }}"

- include_tasks: install-mac.yml
  when: chezmoi_install and ansible_system == "Darwin"

- include_tasks: install-linux.yml
  when: chezmoi_install and ansible_system == "Linux"

- include_tasks: configure.yml
  tags:
    - configure
